game_rooms = [
    [{"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'A1'},
     {"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'A2'},
     {"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'A3'},
     {"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'A4'},
     ],
    [{"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'B1'},
     {"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'B2'},
     {"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'B3'},
     {"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "Visited": False, "current": False, "id": 'B4'},
     ],
    [{"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'C1'},
     {"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'C2'},
     {"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'C3'},
     {"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'C4'},
     ],
    [{"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'D1'},
     {"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'D2'},
     {"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'D3'},
     {"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'D4'},
     ],
    [{"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'E1'},
     {"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'E2'},
     {"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'E3'},
     {"room_name": "", "start": False, "goal": False, "entity": None, "monster": None, "loot": None, "visited": False, "current": False, "id": 'E4'},
     ],
]

game_world_name_one = [
    "Blood",
    "Barrow",
    "Heaven",
    "Hallow",
    "Star",
    "Talon",
    "Sun",
    "Dark",
    "Black",
]

game_world_name_two = [
    "Land",
    "Wind",
    "Isle",
    "Haven",
    "Earth",
    "Fire",
    "Realm",
    "Glade",
    "Edge",
    "Wastes",
    "Coast",
]

game_helper = [
    "Mogdred",
    "Zargon",
    "Balthar",
    "Rabius",
    "Daltar",
    "Zoltan",
    "Cassandra",
    "Altron",
]

game_room_types = {
    "Library": ["book", "scroll"],
    "Armory": ["weapon", "armor", "shield"],
    "Kitchen": ["food", "potion", "drink"],
    "Hallway": ["misc", "shield"],
    "Chapel": ["book", "scroll", "jewelry", "drink"],
    "Laboratory": ["book", "potion", "misc"],
    "Great Hall": ["food", "potion", "armor", "weapon"],
    "Gatehouse": ["shield", "weapon", "food", "drink"],
    "Dungeon": ["misc", "weapon", "food"],
    "Storage": ["food", "misc", "potion"],
    "Courtyard": ["bow"],
    "Bedroom": ["food"],
    "Master Bedroom": ["food", "weapon"],
    "Guardhouse": ["weapon", "shield", "armor", "bow"],
    "Wine Cellar": ["potion", "drink"],
    "Root Cellar": ["food"],
    "Stairwell": [],
    "Garden": ["bow"],
    "Barracks": ["armor", "weapon", "shield"],
    "Stables": ["misc"],
}
