classes = {
    "a": {"name": "Assassin",
          "strength": 4,
          "dexterity": 4,
          "intelligence": 1,
          "wisdom": 1,
          "charisma": 0,
          "items": ["Katana"],
          "spells": ["Stealth", "Invisibility"]
          },
    "b": {"name": "Barbarian",
          "strength": 7,
          "dexterity": 3,
          "intelligence": 0,
          "wisdom": 0,
          "charisma": 0,
          "items": ["Axe"],
          "spells": ["Berserk"]
          },
    "c": {"name": "Cleric",
          "strength": 2,
          "dexterity": 2,
          "intelligence": 3,
          "wisdom": 3,
          "charisma": 0,
          "items": ["Dagger"],
          "spells": ["Spurt", "Greater Heal", "Magic Arrow"]
          },
    "d": {"name": "Druid",
          "strength": 1,
          "dexterity": 2,
          "intelligence": 3,
          "wisdom": 4,
          "charisma": 0,
          "items": ["Staff"],
          "spells": ["Spurt", "Greater Heal", "Amber Spear"]
          },
    "e": {"name": "Enchanter",
          "strength": 0,
          "dexterity": 1,
          "intelligence": 5,
          "wisdom": 2,
          "charisma": 2,
          "items": [],
          "spells": ["Blind", "Life To Mana", "Mind Blast"]
          },
    "f": {"name": "Fighter",
          "strength": 5,
          "dexterity": 3,
          "intelligence": 1,
          "wisdom": 0,
          "charisma": 1,
          "items": ["Sword", "Helmet"],
          "spells": []
          },
    "g": {"name": "Guardian",
          "strength": 4,
          "dexterity": 2,
          "intelligence": 1,
          "wisdom": 2,
          "charisma": 1,
          "items": ["Sword", "Shield"],
          "spells": []
          },
    "h": {"name": "Healer",
          "strength": 1,
          "dexterity": 2,
          "intelligence": 4,
          "wisdom": 3,
          "charisma": 0,
          "items": ["Cudgel"],
          "spells": ["Greater Heal", "Heal", "Meditate"]
          },
    "i": {"name": "Illusionist",
          "strength": 1,
          "dexterity": 1,
          "intelligence": 3,
          "wisdom": 4,
          "charisma": 1,
          "items": ["Staff"],
          "spells": ["Lesser Heal", "Blind", "Distract"]
          },
    "j": {"name": "Jester",
          "strength": 2,
          "dexterity": 2,
          "intelligence": 3,
          "wisdom": 2,
          "charisma": 1,
          "items": ["Jester Hat"],
          "spells": ["Laugh Of Damnation"]
          },
    "k": {"name": "Knight",
          "strength": 6,
          "dexterity": 3,
          "intelligence": 1,
          "wisdom": 0,
          "charisma": 0,
          "items": ["Chainmail Armor", "Great Sword"],
          "spells": []
          },
    "l": {"name": "Lancer",
          "strength": 4,
          "dexterity": 3,
          "intelligence": 1,
          "wisdom": 2,
          "charisma": 0,
          "items": ["Leather Armor", "Spear"],
          "spells": []
          },
    "m": {"name": "Magician",
          "strength": 0,
          "dexterity": 1,
          "intelligence": 6,
          "wisdom": 3,
          "charisma": 0,
          "items": ["Staff"],
          "spells": ["Spurt", "Fireball", "Heal"]
          },
    "n": {"name": "Necromancer",
          "strength": 2,
          "dexterity": 1,
          "intelligence": 3,
          "wisdom": 4,
          "charisma": 0,
          "items": ["Staff"],
          "spells": ["Curse", "Life Leech", "Death"]
          },
    "o": {"name": "Occultist",
          "strength": 3,
          "dexterity": 3,
          "intelligence": 2,
          "wisdom": 2,
          "charisma": 0,
          "items": ["Demonic Dagger"],
          "spells": ["Curse", "Life Leech"]
          },
    "p": {"name": "Paladin",
          "strength": 4,
          "dexterity": 2,
          "intelligence": 2,
          "wisdom": 2,
          "charisma": 0,
          "items": ["Splinted Armor", "Sword"],
          "spells": ["Spurt", "Heal", "Curse"]
          },
    "q": {"name": "Quarrelist",
          "strength": 1,
          "dexterity": 2,
          "intelligence": 2,
          "wisdom": 1,
          "charisma": 4,
          "items": ["Dagger"],
          "spells": ["Distract"]
          },
    "r": {"name": "Rogue",
          "strength": 2,
          "dexterity": 4,
          "intelligence": 2,
          "wisdom": 1,
          "charisma": 1,
          "items": ["Bow", "Dagger"],
          "spells": ["Spurt", "Invisibility"]
          },
    "s": {"name": "Sorcerer",
          "strength": 1,
          "dexterity": 0,
          "intelligence": 5,
          "wisdom": 4,
          "charisma": 0,
          "items": ["Staff"],
          "spells": ["Spurt", "Lesser Heal", "Energy Bolt"]
          },
    "t": {"name": "Thief",
          "strength": 1,
          "dexterity": 3,
          "intelligence": 2,
          "wisdom": 3,
          "charisma": 1,
          "items": ["Dagger"],
          "spells": ["Spurt", "Steal", "Stealth"]
          },
    "u": {"name": "Undying",
          "strength": 2,
          "dexterity": 2,
          "intelligence": 3,
          "wisdom": 3,
          "charisma": 0,
          "items": ["Mace", "Talisman of Undying"],
          "spells": ["Meditate"]
          },
    "v": {"name": "Vagabond",
          "strength": 2,
          "dexterity": 2,
          "intelligence": 1,
          "wisdom": 2,
          "charisma": 3,
          "items": [],
          "spells": []
          },
    "w": {"name": "Warlock",
          "strength": 1,
          "dexterity": 0,
          "intelligence": 5,
          "wisdom": 4,
          "charisma": 0,
          "items": ["Staff"],
          "spells": ["Spurt", "Lesser Heal", "Eldritch Blast"]
          },
    "x": {"name": "Xarax",
          "strength": 2,
          "dexterity": 2,
          "intelligence": 2,
          "wisdom": 2,
          "charisma": 2,
          "items": ["Sword", "Talisman of Xarax"],
          "spells": ["Lesser Heal", "Meditate"]
          },
    "y": {"name": "Yithian",
          "strength": 1,
          "dexterity": 1,
          "intelligence": 5,
          "wisdom": 3,
          "charisma": 0,
          "items": [],
          "spells": ["Heal", "Eldritch Blast"]
          },
    "z": {"name": "Zealot",
          "strength": 2,
          "dexterity": 3,
          "intelligence": 2,
          "wisdom": 3,
          "charisma": 0,
          "items": ["Whip"],
          "spells": ["Spurt", "Immolate", "Meditate"]
          },
}

game_spells = {
    "Spurt": {"Damage": -0.5, "Mana": -0.5, "Wisdom": 0, "Type": "Water"},
    "Immolate": {"Special": "Burn", "Damage": 1, "Mana": -2, "Wisdom": 3, "Type": "Fire"},
    "Meditate": {"Mana": 0.5, "Wisdom": 2, "Type": "Skill"},
    "Eldritch Blast": {"Damage": -3, "Mana": -2},
    "Lesser Heal": {"Heal": 1, "Mana": -1, "Wisdom": 1, "Type": "Healing"},
    "Stealth": {"Special": "Stealth", "Mana": -1, "Wisdom": 0, "Type": "Skill"},
    "Steal": {"Special": "Steal", "Mana": -0.5, "Wisdom": 0, "Type": "Skill"},
    "Energy Bolt": {"Damage": -2.5, "Mana": -2, "Wisdom": 4, "Type": "Arcane"},
    "Invisibility": {"Special": "Run", "Mana": -2, "Wisdom": 1, "Type": "Skill"},
    "Curse": {"Damage": -1, "Mana": -0.5, "Wisdom": 2, "Type": "Curse"},
    "Heal": {"Heal": 2, "Mana": -2, "Wisdom": 2, "Type": "Healing"},
    "Life Leech": {"Damage": 1, "Heal": 1, "Mana": -1, "Wisdom": 3, "Type": "Necromancy"},
    "Death": {"Damage": 2, "Mana": -1.5, "Wisdom": 4, "Type": "Necromancy"},
    "Laugh Of Damnation": {"Damage": 1, "Mana": 1, "Wisdom": 1, "Type": "Curse"},
    "Fireball": {"Damage": 1, "Mana": -1, "Wisdom": 3, "Type": "Fire"},
    "Distract": {"Special": "Run", "Mana": -2, "Wisdom": 2, "Type": "Curse"},
    "Blind": {"Special": "Blind", "Mana": -1, "Wisdom": 2, "Type": "Curse"},
    "Greater Heal": {"Heal": 3, "Mana": -2, "Wisdom": 3, "Type": "Healing"},
    "Life To Mana": {"Heal": -1, "Mana": 1, "Wisdom": 1, "Type": "Mana Regen"},
    "Amber Spear": {"Damage": 2, "Mana": -1, "Wisdom": 2, "Type": "Earth"},
    "Magic Arrow": {"Damage": 1.5, "Mana": -1, "Wisdom": 1, "Type": "Arcane"},
    "Berserk": {"Special": "Rage", "Mana": 0.5, "Wisdom": 0, "Type": "Buff"},
}

game_items = {
    "Sword": {"damage": 1, "equipment": "r_hand", "type": "weapon", "d_type": "slash", "rarity": 1},
    "katana": {"damage": 1.2, "equipment": "r_hand", "type": "weapon", "d_type": "slash", "rarity": 5},
    "Dagger": {"damage": 0.3, "equipment": "l_hand", "type": "weapon", "d_type": "pierce", "rarity": 0},
    "Demonic Dagger": {"damage": 0.3, "equipment": "l_hand", "type": "weapon", "d_type": "pierce", "special": "curse",
                       "rarity": 4},
    "Axe": {"damage": 1., "equipment": "r_hand", "type": "weapon", "d_type": "cleave", "rarity": 1},
    "Club": {"damage": 0.5, "equipment": "r_hand", "type": "weapon", "d_type": "blunt", "rarity": 0},
    "Staff": {"damage": 0.5, "equipment": "l_hand", "type": "weapon", "d_type": "blunt", "rarity": 0},
    "Great Axe": {"damage": 1.5, "equipment": "b_hands", "type": "weapon", "d_type": "cleave", "rarity": 3},
    "Short Spear": {"damage": 1, "equipment": "r_hand", "type": "weapon", "d_type": "pierce", "rarity": 2},
    "Spear": {"damage": 1.5, "equipment": "b_hands", "type": "weapon", "d_type": "pierce", "rarity": 4},
    "Cudgel": {"damage": 0.5, "equipment": "l_hand", "type": "weapon", "d_type": "blunt", "rarity": 1},
    "Mace": {"damage": 1.2, "equipment": "r_hand", "type": "weapon", "d_type": "blunt", "rarity": 2},
    "Whip": {"damage": 0.5, "equipment": "l_hand", "type": "weapon", "d_type": "sting", "special": "whip", "rarity": 4},
    "Great Sword": {"damage": 1.5, "equipment": "b_hands", "type": "weapon", "d_type": "slash", "rarity": 5},
    "Bow": {"damage": 0.5, "equipment": "back", "type": "bow", "d_type": "pierce", "rarity": 2},
    "War Bow": {"damage": 0.7, "equipment": "back", "type": "bow", "d_type": "pierce", "rarity": 4},
    "Buckler": {"dam_reduction": 0.2, "equipment": "l_hand", "type": "shield", "rarity": 0},
    "Shield": {"dam_reduction": 0.4, "equipment": "l_hand", "type": "shield", "rarity": 2},
    "Kite Shield": {"dam_reduction": 0.6, "equipment": "l_hand", "type": "shield", "rarity": 4},
    "Skull Cap": {"dam_reduction": 0.1, "equipment": "head", "type": "armor", "rarity": 0},
    "Helmet": {"dam_reduction": 0.2, "equipment": "head", "type": "armor", "rarity": 2},
    "Bascinet": {"dam_reduction": 0.4, "equipment": "head", "type": "armor", "rarity": 3},
    "Plate Helm": {"dam_reduction": 0.6, "equipment": "head", "type": "armor", "rarity": 6},
    "Leather Armor": {"dam_reduction": 0.4, "equipment": "body", "type": "armor", "rarity": 1},
    "Splinted Armor": {"dam_reduction": 0.5, "equipment": "body", "type": "armor", "rarity": 2},
    "Ringmail Armor": {"dam_reduction": 0.6, "equipment": "body", "type": "armor", "rarity": 3},
    "Chainmail Armor": {"dam_reduction": 0.8, "equipment": "body", "type": "armor", "rarity": 4},
    "Plate Armor": {"dam_reduction": 1.2, "equipment": "body", "type": "armor", "rarity": 5},
    "Jester Hat": {"equipment": "head", "type": "clothing", "special": "luck", "rarity": 7},
    "Robe": {"dam_reduction": 0.2, "equipment": "body", "type": "clothing", "rarity": 0},
    "Cloak": {"dam_reduction": 0.1, "equipment": "neck", "type": "clothing", "rarity": 3},
    "Scroll": {"type": "scroll", "rarity": 2},
    "Spell Book": {"type": "book", "rarity": 3},
    "Potion": {"type": "potion", "rarity": 0},
    "Talisman": {"type": "jewelry", "rarity": 2},
    "Ring": {"type": "jewelry", "rarity": 4},
}

game_potions = {
    "Small Red Potion": {"restore_health": 2, "restore_mana": 0, "inc_dex": 0, "inc_str": 0, "inc_int": 0,
                         "inc_wis": 0, "inc_char": 0, "poison_damage": 0},
    "Medium Red Potion": {"restore_health": 4, "restore_mana": 0, "inc_dex": 0, "inc_str": 0, "inc_int": 0,
                          "inc_wis": 0, "inc_char": 0, "poison_damage": 0},
    "Large Red Potion": {"restore_health": 6, "restore_mana": 0, "inc_dex": 0, "inc_str": 0, "inc_int": 0,
                         "inc_wis": 0, "inc_char": 0, "poison_damage": 0},
    "Small Blue Potion": {"restore_health": 0, "restore_mana": 2, "inc_dex": 0, "inc_str": 0, "inc_int": 0,
                          "inc_wis": 0, "inc_char": 0, "poison_damage": 0},
    "Medium Blue Potion": {"restore_health": 0, "restore_mana": 4, "inc_dex": 0, "inc_str": 0, "inc_int": 0,
                           "inc_wis": 0, "inc_char": 0, "poison_damage": 0},
    "Orange Potion": {"restore_health": 2, "restore_mana": 2, "inc_dex": 0, "inc_str": 0, "inc_int": 0,
                      "inc_wis": 0, "inc_char": 0, "poison_damage": 0},
    "Yellow Potion": {"restore_health": 0, "restore_mana": 0, "inc_dex": 0, "inc_str": 1, "inc_int": 0,
                      "inc_wis": 0, "inc_char": 0, "poison_damage": 0},
    "White Potion": {"restore_health": 0, "restore_mana": 0, "inc_dex": 1, "inc_str": 0, "inc_int": 0,
                     "inc_wis": 0, "inc_char": 0, "poison_damage": 0},
    "Green Potion": {"restore_health": 0, "restore_mana": 0, "inc_dex": 0, "inc_str": 0, "inc_int": 0,
                     "inc_wis": 1, "inc_char": 0, "poison_damage": 0},
    "Pink Potion": {"restore_health": 0, "restore_mana": 0, "inc_dex": 0, "inc_str": 0, "inc_int": 1,
                    "inc_wis": 0, "inc_char": 0, "poison_damage": 0},
    "Black Potion": {"restore_health": 0, "restore_mana": 0, "inc_dex": 0, "inc_str": 0, "inc_int": 0,
                     "inc_wis": 0, "inc_char": 1, "poison_damage": 0},
    "Small Grey Potion": {"restore_health": 0, "restore_mana": 0, "inc_dex": 0, "inc_str": 0, "inc_int": 0,
                          "inc_wis": 0, "inc_char": 0, "poison_damage": 1},
    "Medium Grey Potion": {"restore_health": 0, "restore_mana": 0, "inc_dex": 0, "inc_str": 0, "inc_int": 0,
                           "inc_wis": 0, "inc_char": 0, "poison_damage": 2},
    "Purple Potion": {"restore_health": 0, "restore_mana": 0, "inc_dex": 1, "inc_str": 1, "inc_int": 1,
                      "inc_wis": 1, "inc_char": 1, "poison_damage": 0},
}

game_monsters = {
    "Goblin": {
        "name": "Goblin",
        "strength": 1,
        "health": 2,
        "max_health": 2,
        "mana": 1,
        "spells": [],
        "difficulty": 0,
        "miss": "Goblin swings wildly!",
        "hit": "Goblin approaches cautiously!",
        "rewards": ["Dagger", "Loaf Of Bread", "Buckler", "Club"],
        "gold": 3,
        "special": None
    },
    "Spiderling": {
        "name": "Spiderling",
        "Strength": 1,
        "health": 2,
        "max_health": 2,
        "mana": 1,
        "spells": [],
        "difficulty": 1,
        "special": "poison",
        "rewards": [],
        "miss": "Spiderling scuttles backwards!",
        "hit": "Spiderling leaps towards you!",
        "gold": 0
    },
    "Gremlin": {"name": "Gremlin",
                "Strength": 2,
                "health": 1,
                "max_health": 1,
                "mana": 1,
                "spells": [],
                "difficulty": 1,
                "rewards": [],
                "miss": "Gremlin laughs manically!",
                "hit": "Gremlin lunges towards you!",
                "gold": 3,
                "special": None
                },
    "Kobold": {"name": "Kobold",
               "Strength": 2,
               "health": 2,
               "max_health": 2,
               "mana": 2,
               "spells": ["Spurt"],
               "difficulty": 1,
               "miss": "Kobold cowers in fear!",
               "hit": "Kobold steps towards you!",
               "rewards": ["Dagger", "Loaf Of Bread", "Buckler", "Short Spear"],
               "gold": 6,
               "special": None
               },
    "Goblin Mage": {"name": "Goblin Mage",
                    "Strength": 1,
                    "health": 2,
                    "max_health": 2,
                    "mana": 4,
                    "spells": ["Spurt", "Curse"],
                    "difficulty": 2,
                    "miss": "Goblin Mage begins to chant!",
                    "hit": "Goblin Mage rubs it's hands together!",
                    "rewards": ["Dagger", "Staff", "Potion", "Scroll"],
                    "gold": 6,
                    "special": None
                    },
    "Zombie": {"name": "Zombie",
               "Strength": 1,
               "health": 3,
               "max_health": 3,
               "mana": 1,
               "spells": [],
               "difficulty": 2,
               "miss": "Zombie staggers forward!",
               "hit": "Zombie reaches towards you !",
               "rewards": ["Dagger", "Axe", "Buckler"],
               "gold": 5,
               "special": None
               },
    "Darkling": {"name": "Darkling",
                 "Strength": 2,
                 "health": 2,
                 "max_health": 2,
                 "mana": 1,
                 "spells": [],
                 "difficulty": 2,
                 "miss": "Darkling growls at you!",
                 "hit": "Darkling lunges towards you!",
                 "rewards": ["Dagger", "Axe", "Buckler"],
                 "gold": 5,
                 "special": None
                 },
    "Serpent": {"name": "Serpent",
                "Strength": 2,
                "health": 3,
                "max_health": 3,
                "mana": 1,
                "spells": [],
                "difficulty": 3,
                "rewards": [],
                "miss": "Serpent flicks out it's tongue!",
                "hit": "Serpent raises it's head!",
                "gold": 0,
                "special": "poison"
                },
    "Troll": {"name": "Troll",
              "Strength": 3,
              "health": 3,
              "max_health": 3,
              "mana": 1,
              "spells": [],
              "difficulty": 3,
              "miss": "Troll raises it's club!",
              "hit": "Troll swings wildly!",
              "rewards": [],
              "gold": 8,
              "special": "regenerate"
              },
    "Giant Spider": {"name": "Giant Spider",
                     "Strength": 3,
                     "health": 3,
                     "max_health": 3,
                     "mana": 1,
                     "spells": [],
                     "difficulty": 3,
                     "miss": "Giant Spider scuttles backwards!",
                     "hit": "Giant spider rears up on it's back legs!",
                     "rewards": [],
                     "gold": 0,
                     "special": "poison"
                     },
    "Darkling Priest": {"name": "Darkling Priest",
                        "Strength": 1,
                        "health": 2,
                        "max_health": 2,
                        "mana": 5,
                        "spells": ["Fireball", "Lesser Heal", "Spurt"],
                        "difficulty": 2,
                        "miss": "Darkling Priest begins to chant!",
                        "hit": "Darkling Priest rubs it's hands together!",
                        "rewards": ["Dagger", "Staff", "Potion"],
                        "gold": 5,
                        "special": None
                        },
    "Imp": {"name": "Imp",
            "Strength": 1,
            "health": 3,
            "max_health": 3,
            "mana": 10,
            "spells": ["Fireball"],
            "difficulty": 3,
            "miss": "Imp steps backwards!",
            "hit": "Imp reveals it's claws!",
            "rewards": [],
            "gold": 5,
            "special": None
            },
    "Dark Cultist": {"name": "Dark Cultist",
                     "Strength": 2,
                     "health": 3,
                     "max_health": 3,
                     "mana": 2,
                     "spells": ["Curse"],
                     "difficulty": 3,
                     "miss": "Dark Cultist begins to chant!",
                     "hit": "Dark Cultist raises it's dagger!",
                     "rewards": ["Dagger"],
                     "gold": 20,
                     "special": None
                     },
    "Cyclops": {"name": "Cyclops",
                "Strength": 4,
                "health": 3,
                "max_health": 3,
                "mana": 1,
                "spells": [],
                "difficulty": 4,
                "miss": "Cyclops raises it's club!",
                "hit": "Cyclops swings wildly!",
                "rewards": [],
                "gold": 10,
                "special": None
                },
    "Dark Knight": {"name": "Dark Knight",
                    "Strength": 3,
                    "health": 3,
                    "max_health": 3,
                    "mana": 2,
                    "spells": ["Curse"],
                    "difficulty": 4,
                    "miss": "Dark Knight raises it's shield!",
                    "hit": "Dark Knight lunges forward!",
                    "rewards": ["Plate Armor", "Sword", "Mace", "Kite Shield"],
                    "special": "weaken",
                    "gold": 15,
                    },
    "Giant Serpent": {"name": "Giant Serpent",
                      "Strength": 2,
                      "health": 5,
                      "max_health": 5,
                      "mana": 1,
                      "spells": [],
                      "difficulty": 4,
                      "miss": "Giant Serpent flicks out it's tongue!",
                      "hit": "Giant Serpent raises it's head!",
                      "rewards": [],
                      "gold": 0,
                      "special": "poison"
                      },
    "Necromancer": {"name": "Necromancer",
                    "Strength": 2,
                    "health": 4,
                    "max_health": 5,
                    "mana": 1,
                    "spells": ["Curse", "Life Leech", "Death"],
                    "difficulty": 4,
                    "hit": "Necromancer begins to chant!",
                    "miss": "Necromancer rubs it's hands together!",
                    "rewards": ["Staff", "Scroll", "Spell Book"],
                    "gold": 8,
                    "special": None
                    },
}
